# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [4]:
import numpy as np
a = np.random.randint(10, size=6)
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
print('-------------------------')
b = np.random.randint(10, size=6).reshape(2,3)
print('list(b): ', list(b))
print('tolist(): ', b.tolist())

list(a):  [6, 7, 3, 2, 7, 1]
tolist():  [6, 7, 3, 2, 7, 1]
-------------------------
list(b):  [array([2, 3, 3]), array([1, 4, 7])]
tolist():  [[2, 3, 3], [1, 4, 7]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [5]:
# 記得先 Import 正確的套件
import numpy as np

In [11]:
c = np.random.randint(10, size=6) 

print(c)

print('陣列有多少維度:',c.ndim)
print('每個維度的大小:',c.shape)
print('陣列當中有幾個元素:',c.size)
print('陣列中的資料型態:',c.dtype)
print('陣列中每個元素佔用的空間:',c.itemsize)
print(len(c))
print(type(c))

[0 5 8 3 9 9]
陣列有多少維度: 1
每個維度的大小: (6,)
陣列當中有幾個元素: 6
陣列中的資料型態: int64
陣列中每個元素佔用的空間: 8
6
<class 'numpy.ndarray'>


In [12]:
d = np.random.randint(10, size=(3,4)) 

print(d)

print('陣列有多少維度:',d.ndim)
print('每個維度的大小:',d.shape)
print('陣列當中有幾個元素:',d.size)
print('陣列中的資料型態:',d.dtype)
print('陣列中每個元素佔用的空間:',d.itemsize)
print(len(d))
print(type(d))


[[6 8 6 4]
 [3 4 3 1]
 [5 0 0 0]]
陣列有多少維度: 2
每個維度的大小: (3, 4)
陣列當中有幾個元素: 12
陣列中的資料型態: int64
陣列中每個元素佔用的空間: 8
3
<class 'numpy.ndarray'>


In [13]:
e = np.random.randint(10, size=(2,3,2)) 

print(e)

print('陣列有多少維度:',e.ndim)
print('每個維度的大小:',e.shape)
print('陣列當中有幾個元素:',e.size)
print('陣列中的資料型態:',e.dtype)
print('陣列中每個元素佔用的空間:',e.itemsize)
print(len(e))
print(type(e))

[[[9 7]
  [4 3]
  [6 2]]

 [[1 0]
  [2 8]
  [2 6]]]
陣列有多少維度: 3
每個維度的大小: (2, 3, 2)
陣列當中有幾個元素: 12
陣列中的資料型態: int64
陣列中每個元素佔用的空間: 8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [16]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for i in iterable:
        newlist.append(tolist(i))
    return list(newlist)

print(tolist(c))
print(tolist(d))
print(tolist(e))

[0, 5, 8, 3, 9, 9]
[[6, 8, 6, 4], [3, 4, 3, 1], [5, 0, 0, 0]]
[[[9, 7], [4, 3], [6, 2]], [[1, 0], [2, 8], [2, 6]]]
