# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [4]:
import numpy as np
print(np.zeros((2, 3)))
print('----------------')
print(np.empty((2, 3)))
'''np.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列。
np.empty 可以用於只是想要初始化，但之後就會數值覆寫過的形況。'''

[[0. 0. 0.]
 [0. 0. 0.]]
----------------
[[0. 0. 0.]
 [0. 0. 0.]]


'np.zeros((2, 3)) 會產生真正的 0；np.empty((2, 3)) 會產生一個近似於 0 的陣列。\nnp.empty 可以用於只是想要初始化，但之後就會數值覆寫過的形況。'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [5]:
# 記得先 Import 正確的套件

import numpy as np

In [10]:
# 參考解答

a = np.random.rand(2, 3)
np.round(a*10)


array([[ 8., 10.,  3.],
       [ 8.,  8.,  3.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [15]:
m = 20
n = 40

b = np.random.randint(m,n,6).reshape(2,3)

In [16]:
b

array([[23, 35, 34],
       [29, 32, 36]])